name: xtracker
description: "generic tracker app"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # DeviceStorage
  flutter_secure_storage: ^9.2.4

  # AppInfo
  package_info_plus: ^8.1.3

  # SimpleLogging
  # determine paths like tmp or app data
  path_provider: ^2.0.15
  # zip files
  flutter_archive: ^6.0.3
  logger: ^2.5.0
  # call native share dialog
  share_plus: ^10.0.0

  #
  flutter_colorpicker: ^1.1.0

  # UUID generation (ids for model)
  uuid: ^4.5.1
  provider: ^6.1.2

  # 2d grid
  linked_scroll_controller: ^0.2.0

  # chart
  fl_chart: ^0.70.2

  # data storage
  sembast: ^3.8.3
  sembast_web: ^2.4.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # launcher icon
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logos/eagle_logo.png
    - assets/images/logos/ca_logo.png
    - assets/images/logos/exploratia_logo.png
    - assets/images/logos/app_logo.png
    - assets/images/logos/app_logo_white.png

# launcher icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "resources/app_icon_source.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#f0f0f0"
  adaptive_icon_foreground: "resources/app_icon_source.png"