name: xtracker
description: "generic tracker app"
repository: https://github.com/exploratia/xtracker
homepage: https://exploratia.de/xtracker.php

funding:
  - https://buymeacoffee.com/exploratia

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.2.1+9

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  #  flutter_localizations:
  #    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # EasyLocalization
  easy_localization: ^3.0.7+1

  # DeviceStorage
  flutter_secure_storage: ^9.2.4

  # AppInfo
  package_info_plus: ^8.1.3

  # DeviceInfo
  device_info_plus: ^11.5.0

  # SimpleLogging
  # determine paths like tmp or app data
  path_provider: ^2.0.15
  # zip files
  flutter_archive: ^6.0.3
  logger: ^2.5.0

  # call native share dialog
  share_plus: ^11.0.0

  # color picker
  flutter_colorpicker: ^1.1.0

  # UUID generation (ids for model)
  uuid: ^4.5.1

  # provider
  provider: ^6.1.2

  # 2d grid
  linked_scroll_controller: ^0.2.0

  # chart
  fl_chart: ^1.0.0

  # data storage
  sembast: ^3.8.3
  sembast_web: ^2.4.0+4

  # file picker
  file_picker: ^10.1.2

  # url launcher
  url_launcher: ^6.3.1

  # display HTML in flutter
  simple_html_css: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # build assets
  flutter_gen_runner: any
  build_runner: any

  # splash
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/bmc/
    - assets/images/logos/
    - assets/images/trend/
    - assets/translations/
    - assets/infos/

# asset constants generation
flutter_gen:
  line_length: 160
  output: lib/generated/
  #    package_parameter_enabled: true
  assets:
    exclude:
      - assets/translations/**

flutter_native_splash:
  android: true
  ios: false

  color: "#06041f"
  image: assets/images/logos/app_logo.png
  android_12:
    color: "#06041f"
    color_dark: "#06041f"
    icon_background_color: "#06041f"
    image: resources/android12splash.png
