name: littletracker
description: "generic tracker app"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # DeviceStorage
  flutter_secure_storage: ^9.2.4

  # AppInfo
  package_info_plus: ^8.1.3

  # SimpleLogging
  # determine paths like tmp or app data
  path_provider: ^2.0.15
  # zip files
  flutter_archive: ^6.0.3
  logger: ^2.5.0
  # call native share dialog
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logos/eagle_logo.jpg
    - assets/images/logos/ca_logo.jpg
    - assets/images/logos/exploratia_logo.jpg
    - assets/images/logos/app_logo.png
    - assets/images/logos/app_logo_white.png
